name: Publish USPU

on:
  push:
    branches: [ master ]
    paths:
      - "tools/**"
      - ".github/workflows/uspu.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Build with dotnet
      run: dotnet publish --configuration Release -o uspu/
      working-directory: ./tools/SearchPathsUpdater
    - run: mkdir extension
    - name: Upload USPU
      uses: actions/upload-artifact@v1.0.0
      with:
        name: uspu
        path: tools/SearchPathsUpdater/uspu
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   with: 
    #     name: 'USPU CI Build'
    #     files: |
    #       SearchPathsUpdater/uspu/uspu.exe
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}